### ISSUE TITLE
Stint does not compile on latest Nim devel (2.1.1)

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [status-im/nim-stint#140]
To reproduce simply install Nim devel, and compile `import stint`.

```nim
/home/chronos/.nimble/pkgs2/stint-2.0.0-b058d25cbdd163deb425ed14eabe606efa211eca/stint/private/primitives/addcarry_subborrow.nim(116, 11) Error: redefinition of 'dblPrec'; previous declaration here: /home/chronos/.nimble/pkgs2/stint-2.0.0-b058d25cbdd163deb425ed14eabe606efa211eca/stint/private/primitives/addcarry_subborrow.nim(109, 9)
```

Nim version:
```nim
Nim Compiler Version 2.1.1 [Linux: arm64]
Compiled at 2023-08-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b40da812f7aa590ed16df54a492684c228320549
active boot switches: -d:release```

**Comment by mratsim** [comment]
Sounds like an upstream regression, cc @ringabout

The VM is instantiating both sides of ``when nimvm``

https://github.com/status-im/nim-stint/blob/d198ec031e3bae0528c207b8fd801d2b607fdb12/stint/private/primitives/addcarry_subborrow.nim#L105-L118

**Comment by ringabout** [comment]
Cannot reproduce it on Linux 

```nim
import stint
```

```
/home/wind/.nimble/pkgs2/stint-2.0.0-b058d25cbdd163deb425ed14eabe606efa211eca
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-13
```

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Hm... I'm unsure of why this happens then, I did compile Nim from source instead of using a prebuilt binary but hm...

**Comment by jangko** [comment]
We have this issue in nimbus-eth2 targeting arm64.
Not only nim v2. 
nim 1.6.12 also stop compiling with this error.
